spring:
  data:
    mongodb:
      uri: 'mongodb://localhost:27017/amazon-agency'
      auto-index-creation: true

jwt:
  secret: w234ed5rf6gt7yh8ujs43d5fr6tg7yh8uj943sd5f6gh7
  access-token-expiration-seconds: '1440'
  refresh-token-expiration-seconds: '86400'

logging:
  level:
    org:
      springframework:
        web: debug
        security: trace
server:
  servlet:
    context-path: /amazon
